In [1]:
import numpy
import keras.models
import keras.layers

Using TensorFlow backend.


In [33]:
# load the dataset
dataset = numpy.loadtxt('/Users/laurapallett/data/niclas_thomas/pima_diabetes/pima_diabetes.csv', delimiter=',')

# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]

In [34]:
X.shape

(768, 8)

In [83]:
num_features = X.shape[1]

# define the keras model
first_layer_num_nodes = 6
second_layer_num_nodes = 15
output_layer_num_nodes = 1 # must be 1 for binary class output

model = keras.models.Sequential()

first_layer = keras.layers.Dense(first_layer_num_nodes, input_dim=num_features, activation='relu')
model.add(first_layer)

second_layer = keras.layers.Dense(second_layer_num_nodes, activation='tanh')
model.add(second_layer)

output_layer = keras.layers.Dense(output_layer_num_nodes, activation='sigmoid')
model.add(output_layer)

In [84]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [85]:
# fit the keras model on the dataset
model.fit(X, y, epochs=10, batch_size=10)

Epoch 1/10
768/768 [==============================] - 0s 386us/step - loss: 0.9030 - accuracy: 0.3490
Epoch 2/10
768/768 [==============================] - 0s 151us/step - loss: 0.6939 - accuracy: 0.5286
Epoch 3/10
768/768 [==============================] - 0s 173us/step - loss: 0.6437 - accuracy: 0.6641
Epoch 4/10
768/768 [==============================] - 0s 167us/step - loss: 0.6336 - accuracy: 0.6589
Epoch 5/10
768/768 [==============================] - 0s 158us/step - loss: 0.6308 - accuracy: 0.6602
Epoch 6/10
768/768 [==============================] - 0s 165us/step - loss: 0.6285 - accuracy: 0.6602
Epoch 7/10
768/768 [==============================] - 0s 144us/step - loss: 0.6257 - accuracy: 0.6615
Epoch 8/10
768/768 [==============================] - 0s 132us/step - loss: 0.6269 - accuracy: 0.6602
Epoch 9/10
768/768 [==============================] - 0s 214us/step - loss: 0.6276 - accuracy: 0.6602
Epoch 10/10
768/768 [==============================] - 0s 224us/step - loss: 0.622

In [86]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: {:.1f}'.format(accuracy*100))

768/768 [==============================] - 0s 68us/step
Accuracy: 66.3


In [69]:
model.predict(X[0:10,])

array([[0.3391176 ],
       [0.3391176 ],
       [0.33911675],
       [0.3391176 ],
       [0.44550195],
       [0.3366971 ],
       [0.33935964],
       [0.3391176 ],
       [0.36777264],
       [0.26848564]], dtype=float32)

In [70]:
model.predict_classes(X[0:10,])

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int32)

In [71]:
model.predict(X[0:10,])

array([[0.3391176 ],
       [0.3391176 ],
       [0.33911675],
       [0.3391176 ],
       [0.44550195],
       [0.3366971 ],
       [0.33935964],
       [0.3391176 ],
       [0.36777264],
       [0.26848564]], dtype=float32)

In [76]:
second_layer.get_weights()

[array([[-0.36184603,  0.4051004 ,  0.2072103 , -0.01480281,  0.17598201,
          0.19062239,  0.5789197 ,  0.22171563, -0.12686458,  0.27612278],
        [-0.04695803,  0.11439729, -0.2074804 ,  0.6053305 , -0.5505459 ,
          0.31436765,  0.48031753, -0.5691207 ,  0.02470875, -0.25086725],
        [ 0.3874157 ,  0.10791135, -0.3413437 ,  0.33914402, -0.35370317,
          0.06285809, -0.42273012,  0.17164153,  0.08407152,  0.38369426],
        [-0.41189292, -0.31466582, -0.09762326, -0.07607884,  0.43528497,
          0.47034538,  0.43348855,  0.33715433,  0.10109462, -0.01968872],
        [ 0.6132358 , -0.5678756 ,  0.5592213 , -0.5940919 , -0.55519515,
         -0.4202004 ,  0.63780224,  0.45543104, -0.617015  , -0.38503835],
        [ 0.21809366, -0.35136506,  0.05638742, -0.30312765,  0.07284471,
         -0.25156608, -0.22909598,  0.4666192 , -0.30980584, -0.22025451]],
       dtype=float32),
 array([ 0.06069943,  0.        ,  0.00996718, -0.03419448, -0.07387971,
         